### ISSUE TITLE
Add "state_data_variables" tab to downloadable CSV

### ISSUE THREAD

**Issue by mariaelkin** [newamericafoundation/newamerica-data-projects#109]
Hey Kirk, can you add the "state_data_variables" tab to the CSV that gets downloaded from the Care Report page? When I downloaded it, it also gave me the "who pays for care" numbers, but not the "types of care" numbers. Can we either include both or neither of those?

**Comment by kjacks** [comment]
@mariaelkin all four sheets should be in there now
