### ISSUE TITLE
Location of map/table icons

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-data-projects#110]
Thoughts on this?
```
.chart-toggle {
    padding: 15px 5px 0px 0px;
    float: right;
}
```
![screen shot 2016-09-27 at 11 42 35 am](https://cloud.githubusercontent.com/assets/13524901/18880944/9f7f2f5c-84a7-11e6-8a74-66a85e931924.png)

Mobile

![screen shot 2016-09-27 at 11 44 12 am](https://cloud.githubusercontent.com/assets/13524901/18880980/bb801f04-84a7-11e6-9990-e03b0c542369.png)

**Comment by kjacks** [comment]
@rossvanderlinde that thing is that those filters disappear when the table is toggled, so where would the icons go in that case?

**Comment by kjacks** [comment]
24px icons and remove top padding
