### ISSUE TITLE
Homegrown Extremism 2. Dot Matrix Chart

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-data-projects#16]
![screen shot 2016-08-26 at 12 12 20 pm](https://cloud.githubusercontent.com/assets/13524901/18012182/6920b32a-6b86-11e6-8024-2dfc8605e636.png)

**Comment by rossvanderlinde** [comment]
**2a. Citizenship Status of Jihadists involved in Terror Plots**
**Dot Matrix Dots:** One for each record in `People` sheet
**Color coding / key:** `citizenship_status` with fields: U.S.-born citizen, Naturalized citizen, Permanent Resident, Immigrant visa (possibly-this is a very small number of people), Nonimmigrant visa, Refugee, Unknown
**Tool Tip Photo:** `headshot` [url] (new field) 
**Tool Tip Name:** `name` [string]
**Tool Tip Citizenship Status:** `citizenship_status`
**Tool Tip Plot:** `terror_plot` [lookup list: Plots DB > Name]
**Tool Tip Victims Killed:** lookup `victims_killed` [integer] via `terror_plot`
**Tool Tip Victims Wounded:** lookup `victims_wounded` [integer] via `terror_plot`
**Tool Tip Plot Outcome:** lookup `plot_status` [closed list] via `terror_plot`
**Tool Tip Summary:** lookup `description` [html] via `terror_plot`

**Comment by rossvanderlinde** [comment]
New square styling displayed in #19

**Comment by rossvanderlinde** [comment]
**2b on hold because it's noted as low priority and not currently incorporated into the narrative.**

**Comment by rossvanderlinde** [comment]
@kjacks can we please reorder the variables in 2a to reflect how it's listed above (and the colors indicated): U.S.-born citizen, Naturalized citizen, Permanent Resident, Immigrant visa, Nonimmigrant visa, Refugee, Unknown

**Comment by rossvanderlinde** [comment]
@kjacks updated fields above per david's request

**Comment by kjacks** [comment]
@rossvanderlinde 👍
