### ISSUE TITLE
Homegrown Extremism 1. Dot Matrix Chart by Year

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-data-projects#19]
![screen shot 2016-08-25 at 10 28 23 am](https://cloud.githubusercontent.com/assets/13524901/17973000/ba991bc6-6aae-11e6-9198-6d51ff3b458e.png)

**Comment by rossvanderlinde** [comment]
**1a. Jihadists Charged, Deceased, and Indicted**
**Dot Matrix Dots:** One for each record in `People` sheet, segmented by date (`year_indicted`) and then ordered by `person_ID`
**Color coding / key:** `outcome_for_person` with fields: Deceased #e75c64, Charged, Foreign Charge
**Tool Tip Photo:** `headshot` [url] - new field
**Tool Tip Name:** `name` [string]
**Tool Tip Citizenship Status:** `citizenship_status` [closed list]
**Tool Tip Plot:** `terror_plot` [lookup list: Plots DB > Name]
**Tool Tip Victims Killed:** lookup `victims_killed` [integer] via `terror_plot`
**Tool Tip Victims Wounded:** lookup `victims_wounded` [integer] via `terror_plot`
**Tool Tip Plot Outcome:** lookup `plot_status` [closed list] via `terror_plot`
**Tool Tip Summary:** lookup `description` [html] via `terror_plot`

**Comment by rossvanderlinde** [comment]
![screen shot 2016-08-25 at 10 28 23 am](https://cloud.githubusercontent.com/assets/13524901/18005870/ab9497f6-6b6a-11e6-9e48-7e41594bb85f.png)

**Comment by rossvanderlinde** [comment]
**1b. Awlaki over time**

**Title:** Homegrown Extremists Influenced by Anwar al-Awlaki
**Subtitle:** TK

**Dot Matrix Dots:** One for each record in `People` sheet, segmented by date (`year_charged_or_deceased`), then alphabetized by `last_name`. Vertical dividing line separates 2011 and 2012, noting that 2012 is 'Post al-Awlaki' period.
**Color coding / key:** `charged_or_deceased` with fields: Not Influenced by al-Awlaki (NA-Turquoise - #2ebcb3), Influenced by al-Awlaki (Cinnabar Red - #e75c64)

**Tool Tip Photo:** `headshot` [url].
**Tool Tip Name:** `full_name` [string].
**Tool Tip Status:** `outcome_for_person` [closed list].
**Tool Tip Al-Awlaki Ties:** If `char_awlaki_ties`=Yes, "Influenced by al-Awlaki", else if `char_awlaki_contact`=Yes, "In Contact with al-Awlaki", else "None known."
**Tool Tip Date Charged:** `date_charged` [date]. Note: exclude field if not entry or never charged.
**Tool Tip Plot:** `plot_ID` [lookup list: terror_plots sheet > plot_ID].
**Tool Tip Summary:** lookup `description` [html] via `terror_plots` sheet. Note: alternatively, the plot_ID field could be linked to a full plot profile (this raises the "pages not on Wagtail" problem.)

**Table:** To be confirmed.

**Comment by rossvanderlinde** [comment]
Feedback from David: I think this is definitely the way to go.  Also maybe we should retitle "influenced by Awlaki" to "Influenced by Awlaki without direct contact" or similar and we need to make sure that the input doesn't double count the contact people who would always be both.

**Comment by rossvanderlinde** [comment]
**1d. Gender by Year**

**Title:** Homegrown Extremists, by Gender
**Subtitle:** TK

**Dot Matrix Dots:** One for each record in `People` sheet, segmented by date (`year_charged_or_deceased`), then alphabetized by `gender`
**Color coding / key:** `charged_or_deceased` with fields: Female (NA-Turquoise - #2ebcb3), Male (Light Grey - #ddd).

**Tool Tip Photo:** `headshot` [url].
**Tool Tip Name:** `full_name` [string].
**Tool Tip Status:** `outcome_for_person` [closed list].
**Tool Tip Gender:** `gender` [closed list].
**Tool Tip Date Charged:** `date_charged` [date]. Note: exclude field if not entry or never charged.
**Tool Tip Plot:** `plot_ID` [lookup list: terror_plots sheet > plot_ID].
**Tool Tip Summary:** lookup `description` [html] via `terror_plots` sheet. Note: alternatively, the plot_ID field could be linked to a full plot profile (this raises the "pages not on Wagtail" problem.)

**Table:** Same fields as tool tip.

**Comment by rossvanderlinde** [comment]
@kjacks is 1d ready? Or is that post-launch?

**Comment by rossvanderlinde** [comment]
For awlaki, can we add total number next to ties, contact, and none in legend

**Comment by rossvanderlinde** [comment]
Requested addition to 1d @kjacks 

![screen shot 2016-09-13 at 11 20 52 am](https://cloud.githubusercontent.com/assets/13524901/18479776/3f4e3348-79a4-11e6-8a1a-59dd4d8269a4.png)

**Comment by kjacks** [comment]
@rossvanderlinde I feel like this one might make more sense as percent figures next to the male/female labels in the legend?

**Comment by rossvanderlinde** [comment]
Let's add 92% male and 8% female to the legend instead.
