### ISSUE TITLE
Homegrown Extremism 3. Dot Matrix Histogram

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-data-projects#32]
![screen shot 2016-09-01 at 4 18 35 pm](https://cloud.githubusercontent.com/assets/13524901/18182879/c350f26e-705f-11e6-86f2-a2192c6449a9.png)

**3a Homegrown Extremists by Age**
**Dot Matrix Dots:** One for each record in `People` sheet
**Color coding / key:** `marital_status` with possible values: Unmarried, Married, Divorced, Split, Widowed, Unknown
**Tool Tip Photo:** `headshot` [url] - new field
**Tool Tip Name:** `name` [string]
**Tool Tip Marital Status:** `marital_status` [closed list]
**Tool Tip Plot:** `terror_plot` [lookup list: Plots DB > Name]
**Tool Tip Summary:** lookup `description` [html] via `terror_plot`

Table: Same variables as tooltip.

**Comment by rossvanderlinde** [comment]
![screen shot 2016-09-01 at 4 41 09 pm](https://cloud.githubusercontent.com/assets/13524901/18183562/f12b3a5c-7062-11e6-926a-62d5d66804f6.png)

**Comment by rossvanderlinde** [comment]
@kjacks for 3a, can we just exclude everyone without a specified age please. Currently they're being added to 70+

**Comment by kjacks** [comment]
@rossvanderlinde good catch, I'll see what's going on there

**Comment by rossvanderlinde** [comment]
New var ordering from David, @kjacks: Married (turquoise), widowed (blue), divorced (orchid), split (red), unmarried (black), unknown (grey)

**Comment by rossvanderlinde** [comment]
@kjacks instead of an additional factbox for this can we do this (per David's request):

![screen shot 2016-09-13 at 11 14 00 am](https://cloud.githubusercontent.com/assets/13524901/18479493/47dfe39a-79a3-11e6-9f68-b62c9f655fce.png)

**Comment by rossvanderlinde** [comment]
Also reminder about new ordering and colors mentioned above @kjacks 
Thanks!

**Comment by kjacks** [comment]
@rossvanderlinde will definitely change the colors/order.  As for the percent figures, it's definitely something we can do - I worry a little bit that it seems almost the same as the fact boxes and we're just adding unneeded complexity - but if it is a high priority than we cna go ahead with it.

**Comment by rossvanderlinde** [comment]
Color/order changes YES
Fact boxes HOLD

**Comment by rossvanderlinde** [comment]
Var ordering and colors -- @kjacks: Married (mid turquoise), widowed (turquoise), divorced (blue), split (orchid), unmarried (red), unknown (grey)
