### ISSUE TITLE
Left/right scrolling on visualizations

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-data-projects#40]
Seems like the simplest solution but let me know what you think

![screen shot 2016-09-07 at 9 18 35 am](https://cloud.githubusercontent.com/assets/13524901/18313308/231b930e-74dc-11e6-9fde-7ecd0b20bce3.png)

`::-webkit-scrollbar {
    -webkit-appearance: none;
    width: 7px;
}
::-webkit-scrollbar-thumb {
    border-radius: 4px;
    background-color: rgba(0,0,0,.2);
    -webkit-box-shadow: 0 0 1px rgba(255,255,255,.2);
}`

**Comment by kjacks** [comment]
@rossvanderlinde absolutely! - looks like there might be limited support on firefox, but I'll try it out

**Comment by rossvanderlinde** [comment]
somewhere between medium and high priority - i.e. if possible by launch
