### ISSUE TITLE
Requested additional feature on terrorist nationality graphic

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-data-projects#53]
![screen shot 2016-09-08 at 11 17 57 am](https://cloud.githubusercontent.com/assets/13524901/18355094/13010154-75b6-11e6-9f10-3fb9055f4b00.png)

**Comment by rossvanderlinde** [comment]
- Split between citizen/permanent resident and all others
- Add headings
- Include percentages

**Comment by kjacks** [comment]
@rossvanderlinde This is definitely something we can do, but will be a bit more time -> cen get to it after the more high priority issues
