### ISSUE TITLE
Requested color changes to gender

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-data-projects#55]
![screen shot 2016-09-08 at 11 37 39 am](https://cloud.githubusercontent.com/assets/13524901/18356027/2f881594-75b9-11e6-9f59-67ac5252f46a.png)

+ requested color change
+ switch order in which they appear so that female appears at the top of the bars

**Comment by rossvanderlinde** [comment]
On hold. Will circle back to David

**Comment by kjacks** [comment]
Coloring Implemented, ordering on hold
