### ISSUE TITLE
Data Projects Footer Design (For Feedback)

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-data-projects#6]
![screen shot 2016-08-15 at 12 00 07 pm](https://cloud.githubusercontent.com/assets/13524901/17670706/481d7fee-62e1-11e6-8a32-531d911d47b1.png)

Incorporates:

- Data set link
- Most recent update
- Project authors
- Full project structure
- (Primary navigation feature:) Prominent links to previous and next sections

**Comment by rossvanderlinde** [comment]
![screen shot 2016-08-15 at 12 45 23 pm](https://cloud.githubusercontent.com/assets/13524901/17671760/a62fdfd2-62e6-11e6-9692-d6857738a1cc.png)

Edits:
* NA-Turquoise headers (idea)

**Comment by rossvanderlinde** [comment]
![sample-design-1-5](https://cloud.githubusercontent.com/assets/13524901/17671855/2398620a-62e7-11e6-8fe8-78b902a3364d.png)

Edits:

* NA-Turquoise headers (idea)
* Mobile/tablet: two versions, one with section nav side-by-side, the other with section nav left/right.

**Comment by rossvanderlinde** [comment]
https://app.asana.com/0/92657677951505/92657677951505 https://app.asana.com/0/92711502709806/92711502709806 https://app.asana.com/0/92711502709794/92711502709794 https://app.asana.com/0/139182771847346/139182771847346 https://app.asana.com/0/93344036160798/93344036160798 interested to hear your feedback on the data projects footer. In particular:
- Is the navigation to the next page sufficiently prominent / intuitive?
- Is there anything obvious missing? Is there anything unnecessarily included?
- Turquoise platform uppercase headers or Simplon bold white headers?
- Mobile nav: side-by-side or above-below section nav?

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment]
(Please provide feedback by Tue Aug 16.)

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by kjacks** [comment]
@rossvanderlinde 
- yes
- it looks great
- I definitely prefer the white headers
- above/below for sure because we are going to have some crazy long section titles

**Comment by rossvanderlinde** [comment]
@tylerrichardett asked to see the turquoise headers in simplon so here they are

![screen shot 2016-08-15 at 1 14 18 pm](https://cloud.githubusercontent.com/assets/13524901/17672471/80777cba-62ea-11e6-9a2d-9bb6498d207a.png)

**Comment by rossvanderlinde** [comment]
(I think I prefer the white headers too, just thought I'd throw that idea out there)

**Comment by rossvanderlinde** [comment]
Comments from Maria

Yes, I think the navigation to the next page looks good. I also like the mini table of contents a lot.

At first I thought I was going to not like the turquoise, but I actually think it's easier to read.

Re: Mobile nav, leaning towards side-by-side.

[--- Commented from Asana.com
#commenter Maria Elkin
---[aa]

**Comment by rossvanderlinde** [comment]
- Could be more prominent. Maybe using the background images behind the text, rather than black?
- Nope.
- Turquoise Simplon bold?
- Above-below.

[--- Commented from Asana.com
#commenter Tyler Richardett
---[aa]

**Comment by rossvanderlinde** [comment]
Nav looks good to me
Turquoise headers
I think side-by-side looks better on mobile but may be too cramped on an actual screen

[--- Commented from Asana.com
#commenter Breck Wills
---[aa]

**Comment by rossvanderlinde** [comment]
![screen shot 2016-08-15 at 1 31 37 pm](https://cloud.githubusercontent.com/assets/13524901/17672894/a5942334-62ec-11e6-8460-5fbf0cacc7c7.png)

^ Background images behind the text. Kirk can confirm how viable that is (I guess it would pull from the intro image -- is that set using featured image?)

**Comment by kjacks** [comment]
While there is an image field associated with a section, It seems like a lot to make every section of every project have an image required. Also the footer is pretty bulky as, so I would hesitate to add too much more?

**Comment by rossvanderlinde** [comment]
Image version in full-width for what it's worth:
![screen shot 2016-08-15 at 2 33 09 pm](https://cloud.githubusercontent.com/assets/13524901/17674848/48681d38-62f5-11e6-87bd-db27eda42905.png)

**Comment by rossvanderlinde** [comment]
@kjacks what I quite like about the image idea is that it brings more attention to where we want the typical user to go next. Since we have control over projects (and set them up) I don't think it would be difficult to ensure that sections have images, and in the rate instance that no images are added I like this grey background approach:

![screen shot 2016-08-15 at 3 13 59 pm](https://cloud.githubusercontent.com/assets/13524901/17676118/f383d7a2-62fa-11e6-9fac-9279de37f953.png)

**Comment by rossvanderlinde** [comment]
If we went with images, here are three different ways they could be incorporated (thinking in particular about how wide screens would handle them)

![screen shot 2016-08-15 at 3 46 08 pm](https://cloud.githubusercontent.com/assets/13524901/17677137/770480a0-62ff-11e6-8034-eda495247f3c.png)
![screen shot 2016-08-15 at 3 45 44 pm](https://cloud.githubusercontent.com/assets/13524901/17677136/770415c0-62ff-11e6-8ad7-7c012357821a.png)
![screen shot 2016-08-15 at 3 43 59 pm](https://cloud.githubusercontent.com/assets/13524901/17677139/770ad978-62ff-11e6-9278-bd19650cd288.png)

**Comment by rossvanderlinde** [comment]
50%

[--- Commented from Asana.com
#commenter Tyler Richardett
---[aa]

**Comment by rossvanderlinde** [comment]
I like 50% too

[--- Commented from Asana.com
#commenter Joanne Zalatoris
---[aa]

**Comment by rossvanderlinde** [comment]
I like 50% too. 

I see the Quality and Availability are listed as $ amounts. Is that a filler-issue? 

I take it that the Shayna and Aron bios are filler?

[--- Commented from Asana.com
#commenter Alieza Durana
---[aa]

**Comment by rossvanderlinde** [comment]
If we want to have an even 10 sections, it might make sense to include limitations in the methodology itself

[--- Commented from Asana.com
#commenter Alieza Durana
---[aa]

**Comment by rossvanderlinde** [comment]
Additional field per dev's request
![screen shot 2016-08-24 at 3 21 31 pm](https://cloud.githubusercontent.com/assets/13524901/17944622/90ba67ec-6a0e-11e6-8cbf-70530c9d0bc2.png)

**Comment by rossvanderlinde** [comment]
50% design approved
