### ISSUE TITLE
[Minor styling] Captions

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-data-projects#68]
.caption { margin-top: 12px; color: rgba(44,47,53,.45); font-size: 15px; line-height: 140%; }
Bumped the font size down one notch and it seems to work better when slightly darker, particularly on grey backgrounds (it can hardly be differentiated currently on grey backgrounds)

![screen shot 2016-09-12 at 9 34 33 am](https://cloud.githubusercontent.com/assets/13524901/18437698/22612f8e-78cc-11e6-93a7-f37601dcff10.png)
![screen shot 2016-09-12 at 9 34 01 am](https://cloud.githubusercontent.com/assets/13524901/18437699/22625666-78cc-11e6-9a40-82daf844ac2b.png)

**Comment by kjacks** [comment]
@rossvanderlinde just to be sure, this would effect captions throughout the site as well
