### ISSUE TITLE
Care Index 5.1 Explore the Index

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-data-projects#7]
![screen shot 2016-08-16 at 11 20 30 am](https://cloud.githubusercontent.com/assets/13524901/17704603/9410a6b6-63a3-11e6-921e-d5ab74258dc7.png)
For feedback:
* Does this layout make intuitive sense? Are the two levels of navigation intuitive?
* Do we need a list view v map view?
* Does the map key make sense? Should the tooltip make use of the relevant color of the data point in some way?
* Instead of a help "?" button I added the definition of the variable to the key. Do we like that approach?
* Do we expect to incorporate some way of downloading an svg of the map, @kjacks?

**Comment by rossvanderlinde** [comment]
Tagging https://app.asana.com/0/81533887166256/81533887166256 https://app.asana.com/0/92657677951505/92657677951505 https://app.asana.com/0/92711502709794/92711502709794 https://app.asana.com/0/92711502709806/92711502709806 https://app.asana.com/0/139182771847346/139182771847346 https://app.asana.com/0/93344036160798/93344036160798 https://app.asana.com/0/113287106465154/113287106465154 https://app.asana.com/0/113884670727566/113884670727566 for feedback

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment]
If you were to click Quality or Availability would the second level of navigation disappear?
I don't think there needs to be a list view especially if they are not trying to rank the states
I like the definition in the key and the pop-up tooltip

[--- Commented from Asana.com
#commenter Breck Wills
---[aa]

**Comment by rossvanderlinde** [comment]
- Mostly. I think the first-level could stand out more. Maybe an approach like the one on this page -- https://www.washingtonpost.com/graphics/lifestyle/national-parks/ (scroll down a bit).
- Depends almost wholly on what the goal is here. If we're trying to just give a snapshot of how awful all 50 states are, no. If we want users to be able to see where their state ranks on each indicator, yes.
- Yes, though I question the color choice. If we're showing shades of bad, they should all be shades of the same color. If we're showing good to bad, they should be green to red.
- Sure.
- N/A

[--- Commented from Asana.com
#commenter Tyler Richardett
---[aa]

**Comment by kjacks** [comment]
@rossvanderlinde: 
- I like the two-level navigation as is
- I'm happy with just the map view, but if bll wants a list as well we can definitely look into it
- happy as is - I'm liking the simplicity of the tooltip
- as long as that variable description isn't crazy long I think that's great

**Comment by rossvanderlinde** [comment]
![screen shot 2016-08-16 at 11 55 30 am](https://cloud.githubusercontent.com/assets/13524901/17706016/66b46900-63a8-11e6-9263-cfce49bc6c94.png)

**Comment by rossvanderlinde** [comment]
https://app.asana.com/0/139182771847346/139182771847346 yes second level would disappear in those cases.
https://app.asana.com/0/92711502709806/92711502709806 will upload a new version shortly based on your feedback

[--- Commented from Asana.com
#commenter Ross van der Linde
---[aa]

**Comment by rossvanderlinde** [comment]
https://app.asana.com/0/58162393990584/58162393990584 
Three examples:
- http://www.samhsa.gov/data/sites/all/modules/samhsa_rmm/images/us_map.jpg
- http://pics3.city-data.com/assets/desktop/maps/states_bg.png
- http://www.pewtrusts.org/en/multimedia/data-visualizations/2013/~/media/data%20visualizations/interactives/2013/immigration/graphics/bluemap.jpg

[--- Commented from Asana.com
#commenter Tyler Richardett
---[aa]

**Comment by rossvanderlinde** [comment]
https://app.asana.com/0/92711502709806/92711502709806 
I like 1 and 3 for sure.
Also just want to throw out there 
some of the hex/circle approaches that specifically focus on making all states equally visible https://clarity-us.com/data-viz-maps-hex-appeal/

[--- Commented from Asana.com
#commenter Kirk Jackson
---[aa]

**Comment by rossvanderlinde** [comment]
Some updated designs for final feedback
![screen shot 2016-08-18 at 11 58 09 am](https://cloud.githubusercontent.com/assets/13524901/17780923/24b37444-653b-11e6-940f-4e3aeabf888e.png)
![screen shot 2016-08-18 at 11 52 26 am](https://cloud.githubusercontent.com/assets/13524901/17780921/24b148f4-653b-11e6-9b63-f0fa19cc822e.png)
![screen shot 2016-08-18 at 11 32 54 am](https://cloud.githubusercontent.com/assets/13524901/17780922/24b31bfc-653b-11e6-9f37-1ed39bfc1a11.png)

**Comment by rossvanderlinde** [comment]
Did you try the map toggle symbol as a little U.S. map instead of a globe? Since it's only U.S. data/mapping

Also, if the tables are sortable by values instead of only alphabetically, are we essentially ranking states? (which I think BLL expressed they don't want to do)

[--- Commented from Asana.com
#commenter Joanne Zalatoris
---[aa]

**Comment by rossvanderlinde** [comment]
Colors:
Red = cost
Purple = quality
Blue = availability
Turquoise = total

**Comment by rossvanderlinde** [comment]
We could definitely look at a US icon.
On sorting: I think it's just a feature that users might find helpful, but we could potentially turn it off for certain columns

**Comment by rossvanderlinde** [comment]
One thing about the US icon: it may be nice to have a consist icon across all of our platforms for both maps and tables, especially since the ability to toggle between both is likely to be a common feature. But since all our maps are not of the US (e.g. ISP data) I'm wondering if it's just better to leave the globe

**Comment by rossvanderlinde** [comment]
You could do a pindrop or a pindrop with a folded map? (https://image.freepik.com/free-icon/placeholder-on-map-paper-in-perspective_318-61698.png) Looks good otherwise, though.

[--- Commented from Asana.com
#commenter Tyler Richardett
---[aa]

**Comment by rossvanderlinde** [comment]
Table cell color coding update:
![screen shot 2016-08-23 at 12 43 21 pm](https://cloud.githubusercontent.com/assets/13524901/17900937/58ebde20-692f-11e6-8552-b90c794d17ac.png)

**Comment by rossvanderlinde** [comment]
![screen shot 2016-08-23 at 1 13 51 pm](https://cloud.githubusercontent.com/assets/13524901/17901992/805b7714-6933-11e6-8665-544802e2e251.png)

Shadow effect on mouseover of state @kjacks

**Comment by rossvanderlinde** [comment]
Those look nice

[--- Commented from Asana.com
#commenter Joanne Zalatoris
---[aa]

**Comment by rossvanderlinde** [comment]
@kjacks confirming variables for this:

Cost in Home: cost_in_home_yearly (column X)
Cost in Center: cost_in_center_yearly (column AB)
Average Cost: average_cost (column AH)
Cost as % of Household Income: cost_as_proportion_of_hhi (column AG)
Cost as % of Minimum Wage: cost_as_proportion_of_min_wage (column AJ)

Quality: quality_total_norm (column AN)

Availability: availability_total_norm (column AP)

Care Index Score: care_index_combined (column AQ)

**Comment by rossvanderlinde** [comment]
I'd suggest these tweaks to the css:
`.filter-group__category { padding: 7px 9px; } ul.filter-group__category-container { text-align: center; } .filter-group__variable { font-size: 16px } .filter-group__variable-list { text-align:center }`

So that instead of this:
![screen shot 2016-09-20 at 1 53 08 pm](https://cloud.githubusercontent.com/assets/13524901/18682283/9d67f60e-7f39-11e6-9065-76f7860f9fe7.png)

We have this:
![screen shot 2016-09-20 at 1 50 30 pm](https://cloud.githubusercontent.com/assets/13524901/18682289/a5b0708e-7f39-11e6-9743-b40b01159adb.png)
