### ISSUE TITLE
[Minor] White space for caption

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-data-projects#89]
Not quite sure what the fix is here yet, just flagging the white bar above the contents panel
![screen shot 2016-09-20 at 6 06 09 pm](https://cloud.githubusercontent.com/assets/13524901/18690623/015114b6-7f5d-11e6-80ef-0578e63863b4.png)

**Comment by kjacks** [comment]
@rossvanderlinde that white line is created by the caption.  If you remove the caption from the image, there will no longer be the white space
